[PR] Fixes #22, #26. Innapropriated behavior of rename when a model is open and when closing application.
ufopleds/DengueME pull request #38
Opened 2017-10-31 18:05 UTC by Guelmisp

This PR solves the innapropriated behavior of rename feature when a different model is opened in editor (issue #22) and when a model is renamed and then the application is closed (issue #26)

Closes #22
Closes #26

2017-10-31 18:06 UTC, Guelmisp commented
@saraiva3 helped me out with this task! 👍

2017-11-01 20:41 UTC, tiagofml requested changes
Please see comments

2017-11-01 20:53 UTC, tiagofml commented
Bug related in issue #22 was not completely solved. The same wrong behavior happens, but using a different flow. Actually, previous release has this related bug, but it was discovered now when testing this PR.

2017-11-03 13:18 UTC, tiagofml approved these changes

2017-11-03 13:24 UTC, merged